### ISSUE TITLE
Attachments fail on leveldb?

### ISSUE THREAD

**Issue by agozie** [nolanlawson/pouchdb-electron#2]
I have images saved as attachments in chrome, after syncing, they fail to open in electron with leveldb. I get `Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range` with `attachments:true`

**Comment by nolanlawson** [comment]
Wow, that is a bug I've never seen before. Can you provide code to reproduce?

**Comment by agozie** [comment]
Just follow the image attachment tutorial at Pouchdb website.

**Comment by nolanlawson** [comment]
Hm, that's not really enough information for me to figure out what's going on (what platform are you on? what part of the guide exactly are you running?) but I can say that, in general, you can avoid this problem by passing in `Blob`s instead of base64-encoded strings. base64-encoded strings are error-prone and tend to work slightly differently in different browsers, whereas PouchDB can store `Blob`s directly in IndexedDB.

**Comment by nolanlawson** [comment]
Closing just to clean up old issues. Please reopen if you have steps to reproduce. Thanks!
